###
POST http://localhost:5000/api/v1/employee-management/user/add-user
content-type: application/json

{
    "full_name": "Tang Trung",
    "phone_number": "1234",
    "email": "trung1223@gmail.com",
    "day_of_birth": "10/02/2001",
    "department_id": "PB00001",
    "role_name": "63732c1e3e5f00fee0aab769",
    "gender": "Nam"
}