###
POST http://localhost:5001/user-admin/add-user
content-type: application/json

{
    "full_name": "Tăng Kiến Trung",
    "phone_number": "0936155348",
    "email": "trungtkt159@gmail.com",
    "day_of_birth": "11/19/2001",
    "department_id": "PB00001",
    "gender": "Nam"
}

# Đăng nhập
###
POST http://localhost:5001/user/login
content-type: application/json

{
    "username": "02200001",
    "password": "123456"
}

# Xem thông tin người dùng
###
GET http://localhost:5001/user/get-user-information

# Đổi mật khẩu
###
PUT http://localhost:5001/user/change-password-require
content-type: application/json

{
    "new_password": "123456789",
    "new_password_confirm": "123456789"
}


# Đổi mật khẩu
###
PUT http://localhost:5001/user/change-password-optional
content-type: application/json

{
    "old_password": "123456789",
    "new_password": "123456",
    "new_password_confirm": "123456"
}

# Gửi yêu cầu đặt lại mật khẩu
###
POST http://localhost:5001/user/request-reset-password
content-type: application/json

{
    "email": "trung123@gmail.com",
    "phone_number": "123"
}

# Đặt lại mật khẩu
###
POST http://localhost:5001/user-admin/reset-password
content-type: application/json

{
    "user_id": "12200001"
}

# Lấy danh sách nhân viên
###
GET http://localhost:5001/user-admin/get-all-users

# Xem chi tiết nhân viên
###
GET http://localhost:5001/user-admin/get-user-detail?user_id=12200001


# Test Microservice
# Lấy thông tin quyền
###
POST http://localhost:5001/service-events
content-type: application/json

{
    "payload": {
        "event": 1,
        "data": {
            "user_id": "12200001"
        }
    }
}