###
POST http://localhost:5003/department/create-department
content-type: application/json

{
    "name": "IT",
    "room": "A0005",
    "description": "Phòng IT đẹp trai"
}

###
GET http://localhost:5003/department/get-all-departments

###
GET http://localhost:5003/department/get-department-detail?department_id=PB00001


###
DELETE http://localhost:5003/department/delete-department?department_id=PB00004

###
PUT http://localhost:5003/department/update-department
content-type: application/json

{   
    "department_id": "PB00001",
    "name": "ITA",
    "room": "223",
    "description": "Phòng IT"
}